version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - ./.env
    environment:
      - TOKEN=${TOKEN}
    ports: 
      - 5000:5000

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 3000:5000
