# Generated by Django 4.0.6 on 2022-07-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='title',
            new_name='link',
        ),
        migrations.AddField(
            model_name='repo',
            name='name',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
    ]
