# Generated by Django 4.0.6 on 2022-07-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch_alter_repo_link_alter_repo_name_pullrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='repo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
